### ISSUE TITLE
Setup VxIngest for new project board

### ISSUE THREAD

**Issue by ian-noaa** [NOAA-GSL/VxIngest#121]
## Problem
We need a way to better manage the project's backlog and to detect new issues that haven't been assigned to anyone

## Solution
Create a new GitHub project board, set up issue templates to correctly apply labels, and add a GitHub action so new issues are added to the board automatically.

## No Go's

* Setting up other projects on this project board
* Producing a finalized project board - we'll be open to modifying the current one to address problems

## Tasks

- [x] #118 
- [x] #120 
- [x] Update the VxIngest labels
- [x] Add new board to this project
- [x] #123 
- [x] Add a Project Board field to replace our "Priority: <level>" labels

**Comment by ian-noaa** [comment]
One thing that occurs to me - is that we could replace our "Priority" labels with Project board priorities. This will make it easier to sort, filter, and group issues by priority in the board.
