### ISSUE TITLE
implement a surface partial sums ingest

### ISSUE THREAD

**Issue by randytpierce** [NOAA-GSL/VxIngest#196]
We need to implement a surface partial sums ingest document. This is a top level task tracking issue. We define tasks here in a task list and convert those tasks to issues.

```[tasklist]
### implement a surface partial sums ingest  Tasks
- [x] https://github.com/NOAA-GSL/VxIngest/issues/197
- [x] https://github.com/NOAA-GSL/VxIngest/issues/199
- [ ] https://github.com/NOAA-GSL/VxIngest/issues/198
- [ ] https://github.com/NOAA-GSL/VxIngest/issues/202
- [ ] https://github.com/NOAA-GSL/VxIngest/issues/203
- [ ] https://github.com/NOAA-GSL/VxIngest/issues/204
- [ ] https://github.com/NOAA-GSL/VxIngest/issues/205
- [x] copy ctc_builder.py to surface_partial_sums_builder.py and modify the new builder to work for partial sums (needs subtasks)
- [ ] create metadata and any necessary indexes
- [ ] implement the ingest process and test results.
- [ ] https://github.com/NOAA-GSL/VxIngest/issues/209
- [ ] https://github.com/NOAA-GSL/VxIngest/issues/208
- [ ] https://github.com/NOAA-GSL/VxIngest/issues/15
```

**Comment by randytpierce** [comment]
This is now finished in branch "197-create-a-partial_sums_to_cb-directory-and-structure-that-is-based-on-the-existing-ctc_to_cb-directory-structure-in-vxingest" which is being merged today. Closing this issue.
